### PR TITLE
Fix for #157: wrong currency transmitted

### LINKED ISSUE #157: Wrong amount/currency, if display currency not equal to base currency
If, for a website in Magento2, the base and display currency differ like here
screen shot 2018-03-07 at 11 55 30

then the capture/authorization request sent to PAYONE is sent using the amount in base currency (eg EUR), but the currency symbol used for the order (eg SEK), such that a wrong amount is invoiced!
payone-sek-fehler

Here is the corresponding code in "Model/Api/Request/Capture.php" and ".../Authorization.php": 
screen shot 2018-03-07 at 11 56 00
screen shot 2018-03-07 at 11 55 49

Please fix this to either send base currency symbol always, or convert amount to currency used in the order!

### PR DESCRIPTION
**Pull request by josefbehr**
Fixes #157 

- added config field to chose currency for transmission (base or default display currency)
- added two methods in Payone\Core\Helper\Toolkit:
    - **convertToTransmitCurrency($amount)** converts from base (order) currency to configured currency
    - **getTransmitCurrencyCode()** returns the corresponding currency code
- added usage of said methods to Capture, Authorization, Debit, and Precheck requests

I hope this helps fix the problem quickly. I chose the toolkit helper since it already seems to be a kind of general purpose helper. If the placement is wrong for any reason, just change it, or tell me and I will. There might be more classes that need to convert an amount, but those four were the most obvious to me.

### CODE REVIEW

File: Helper/Toolkit.php [hunk 1]
```diff
@@ -209,4 +210,62 @@ public function getAdditionalDataEntry(DataObject $oData, $sKey)
...
+        $store = $this->storeManager->getStore();
+
+        // get display currency code and base currency model
+        $targetCurrencyCode = $store->getDefaultCurrencyCode();
+        $baseCurrency = $store->getBaseCurrency();
+
+        try {
+            return $baseCurrency->convert($amount, $targetCurrencyCode);
+        } catch (\Exception $e) {
+            return $amount; // TODO!
```
Comment (josefbehr) [inline Helper/Toolkit.php]: This might not be ideal ;)

**Comment by fjbender** [comment]
Thank you very much for your contribution! We'll review it as soon as possible an maybe come up with a better plan for handling the exception when the currency can't be converted.
