### PR TITLE
Fix missing status in response in case of curl timeouts. Fixes #148

### LINKED ISSUE #148: undefined index: status
If no status is in the response (for whatever reason, service down, timeout maybe) this line fails:

https://github.com/PAYONE-GmbH/magento-2/blob/3ab1564553ff2e694fad914dd60aaf79bd3875f9/Model/Api/Request/Base.php#L287

### PR DESCRIPTION
**Pull request by gerritpechmann**
We sometimes see exceptions when the status is missing in the API response. This is also mentioned in #148 

I would assume if the status is missing we set it to "ERROR". The following code then requires the keys  "errorcode" and "customermessage" set in Model/Methods/PayoneMethod.php line 151

https://github.com/PAYONE-GmbH/magento-2/blob/master/Model/Methods/PayoneMethod.php#L151

### CODE REVIEW

File: Helper/Api.php [hunk 1]
```diff
@@ -148,6 +148,12 @@ public function sendApiRequest($sRequestUrl)
 
         $aResponse = $this->formatOutputByResponse($aResponse);
 
+        if (!array_key_exists('status', $aResponse)) {
+            $aResponse['status'] = 'ERROR';
+            $aResponse['errorcode'] = '903';
```
Comment (fjbender) [inline Helper/Api.php]: I would argue that one shouldn't map this to a (theoretically) possible error code from the Payone platform to avoid confusion. Maybe use errorcode '0' with an appropriate message?

**Comment by hreinberger** [comment]
Hi @gerritpechmann 
I'd also prefer using an error code that's not present on our platform ('0' should be fine). Could you update your accordingly?

**Comment by fjbender** [comment]
Fine with me. @hreinberger can you give this to QA (maybe simulate the case with a different Server-API URL)?

**Comment by hreinberger** [comment]
First tests look promising!

**Comment by hreinberger** [comment]
Thanks for your contribution!
